// AUTO-GENERATED by scripts/brand/generate_ui_module.sh — do not edit by hand.
// Source catalog: src/assets/elements/catalog.json

import heroPerch from "./hero-perch.png";
import createAlarm from "./create-alarm.png";
import setTime from "./set-time.png";
import taskChecklist from "./task-checklist.png";
import running from "./running.png";
import retry from "./retry.png";
import pausedSleep from "./paused-sleep.png";
import sproutFresh from "./sprout-fresh.png";
import themeLight from "./theme-light.png";
import themeDark from "./theme-dark.png";
import chatGlobal from "./chat-global.png";
import multiDevice from "./multi-device.png";
import notifyBadge from "./notify-badge.png";
import logsClipboard from "./logs-clipboard.png";
import successCheck from "./success-check.png";
import syncRefresh from "./sync-refresh.png";

export type ElementId =
  | "hero-perch"
  | "create-alarm"
  | "set-time"
  | "task-checklist"
  | "running"
  | "retry"
  | "paused-sleep"
  | "sprout-fresh"
  | "theme-light"
  | "theme-dark"
  | "chat-global"
  | "multi-device"
  | "notify-badge"
  | "logs-clipboard"
  | "success-check"
  | "sync-refresh";

export const elements: Record<ElementId, string> = {
  "hero-perch": heroPerch,
  "create-alarm": createAlarm,
  "set-time": setTime,
  "task-checklist": taskChecklist,
  running,
  retry,
  "paused-sleep": pausedSleep,
  "sprout-fresh": sproutFresh,
  "theme-light": themeLight,
  "theme-dark": themeDark,
  "chat-global": chatGlobal,
  "multi-device": multiDevice,
  "notify-badge": notifyBadge,
  "logs-clipboard": logsClipboard,
  "success-check": successCheck,
  "sync-refresh": syncRefresh,
};

export function elementSrc(id: ElementId): string {
  return elements[id];
}

export const elementIds = Object.keys(elements) as ElementId[];
