#!/usr/bin/env bash
# Generate src/assets/elements/index.ts (+ ElementImage if missing) from catalog.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

ensure_dirs
write_png_module_decl

if [[ ! -f "${UI_CATALOG}" ]]; then
  die "missing ${UI_CATALOG}; run slice_elements.sh first"
fi

log "generate ${UI_INDEX_TS}"
UI_CATALOG="${UI_CATALOG}" UI_INDEX_TS="${UI_INDEX_TS}" BRAND_ROOT="${BRAND_ROOT}" python3 << 'PY'
import json
import os
import re
from pathlib import Path

catalog_path = Path(os.environ["UI_CATALOG"])
index_path = Path(os.environ["UI_INDEX_TS"])
ui_component = Path(os.environ["BRAND_ROOT"]) / "src" / "ui" / "ElementImage.tsx"

catalog = json.loads(catalog_path.read_text())
elements = catalog["elements"]

def to_ident(name: str) -> str:
    parts = re.split(r"[-_]", name)
    head, *rest = parts
    return head + "".join(p[:1].upper() + p[1:] for p in rest)

out: list[str] = [
    "// AUTO-GENERATED by scripts/brand/generate_ui_module.sh — do not edit by hand.",
    "// Source catalog: src/assets/elements/catalog.json",
    "",
]
for el in elements:
    out.append(f'import {to_ident(el["id"])} from "./{el["file"]}";')
out.append("")
out.append("export type ElementId =")
for i, el in enumerate(elements):
    suffix = ";" if i == len(elements) - 1 else ""
    out.append(f'  | "{el["id"]}"{suffix}')
out.append("")
out.append("export const elements: Record<ElementId, string> = {")
for el in elements:
    key = el["id"]
    ident = to_ident(key)
    if re.search(r"[^A-Za-z0-9_]", key):
        out.append(f'  "{key}": {ident},')
    else:
        out.append(f"  {key},")
out.append("};")
out.append("")
out.append("export function elementSrc(id: ElementId): string {")
out.append("  return elements[id];")
out.append("}")
out.append("")
out.append("export const elementIds = Object.keys(elements) as ElementId[];")
out.append("")
index_path.write_text("\n".join(out))
print(f"wrote {index_path}")

ui_component.parent.mkdir(parents=True, exist_ok=True)
if not ui_component.exists():
    ui_component.write_text(
        """import classNames from \"classnames\";
import { elementSrc, type ElementId } from \"../assets/elements\";

interface Props {
  id: ElementId;
  alt?: string;
  size?: number | string;
  className?: string;
}

/** Presentational bird/alarm illustration from the brand element catalog. */
export function ElementImage({ id, alt = \"\", size = 96, className }: Props) {
  const dim = typeof size === \"number\" ? `${size}px` : size;
  return (
    <img
      src={elementSrc(id)}
      alt={alt}
      className={classNames(\"callai-element\", className)}
      style={{ width: dim, height: \"auto\", display: \"block\", userSelect: \"none\" }}
      draggable={false}
    />
  );
}
"""
    )
    print(f"wrote {ui_component}")
else:
    print(f"keep existing {ui_component}")
PY

log "done: UI module"
